# Generated by Django 5.0.3 on 2024-03-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sentiments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiments',
            name='text',
            field=models.CharField(default='Neutral', max_length=100),
        ),
    ]
